document.addEventListener("DOMContentLoaded",()=>{
const state={reminiscence:0,rize:0,at:0,episode:0,direct:0,lowerReplay:0,within100Trials:0,within100Hits:0,pullbackTrials:0,pullbackHits:0,uraTrials:0,uraHits:0,minSetting:1,odd:0,even:0};
const rates={at:[394.4,380.5,357.0,325.9,291.2,261.3],reminiscence:[300.5,295.1,287.6,276.7,262.7,251.2],rize:[2079.1,1906.5,1722.8,1478.9,1226.6,1074.9],episode:[6620.2,5879.7,5114.5,4062.5,3166.7,2639.5],direct:[28460.6,24453.5,18093.0,12019.5,8615.4,7036.8],lowerReplay:[1260.3,1213.6,1170.3,1129.9,1092.3,1024]};
const percentages={within100:[.1958,.2104,.2315,.2637,.3196,.3601],pullback:[.0781,.0781,.0938,.1094,.125,.1523],ura:[.011,.0132,.0163,.0219,.0285,.0332]};
let totalMode=true;
const $=id=>document.getElementById(id);
function setValue(id,v){state[id]=Math.max(0,v);const e=$(`${id}-value`);if(e)e.textContent=state[id]}
document.querySelectorAll(".counter-btn").forEach(b=>b.addEventListener("click",()=>setValue(b.dataset.target,state[b.dataset.target]+(b.classList.contains("plus")?1:-1))));
$("game-mode")?.addEventListener("click",()=>{totalMode=!totalMode;$("game-mode").classList.toggle("on",totalMode);$("mode-label").textContent=totalMode?"ON":"OFF"});
document.querySelectorAll(".material-grid button,.material-list button").forEach(b=>b.addEventListener("click",()=>{const parent=b.parentElement;parent.querySelectorAll("button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");if(b.dataset.min)state.minSetting=Math.max(state.minSetting,Number(b.dataset.min));if(b.dataset.odd)state.odd++;if(b.dataset.even)state.even++}));
function factorialLog(n){let x=0;for(let i=2;i<=n;i++)x+=Math.log(i);return x}
function pois(g,n,r){if(g<=0)return 0;const l=g/r;return n===0?-l:n*Math.log(l)-l-factorialLog(n)}
function bin(t,h,p){if(t<=0)return 0;const x=Math.max(0,Math.min(h,t)),q=Math.max(.000001,Math.min(.999999,p));return x*Math.log(q)+(t-x)*Math.log(1-q)}
function targetGames(){const g=Number($("games")?.value||0),s=Number($("start-games")?.value||0);return totalMode?g:Math.max(0,g-s)}
function probabilities(){const g=targetGames(),logs=[];for(let i=0;i<6;i++){let x=0;x+=pois(g,state.at,rates.at[i]);x+=pois(g,state.reminiscence,rates.reminiscence[i]);x+=pois(g,state.rize,rates.rize[i]);x+=pois(g,state.episode,rates.episode[i]);x+=pois(g,state.direct,rates.direct[i]);x+=pois(g,state.lowerReplay,rates.lowerReplay[i]);x+=bin(state.within100Trials,state.within100Hits,percentages.within100[i]);x+=bin(state.pullbackTrials,state.pullbackHits,percentages.pullback[i]);x+=bin(state.uraTrials,state.uraHits,percentages.ura[i]);if(i+1<state.minSetting)x-=40;if(state.odd&&i%2===0)x+=.25;if(state.even&&i%2===1)x+=.25;logs.push(x)}const m=Math.max(...logs),w=logs.map(x=>Math.exp(x-m)),sum=w.reduce((a,b)=>a+b,0);return w.map(x=>x/sum*100)}
function render(p){for(let s=1;s<=6;s++){const v=p[s-1]||0;if($(`setting-percent-${s}`))$(`setting-percent-${s}`).textContent=`${Math.round(v)}%`;if($(`setting-bar-${s}`))$(`setting-bar-${s}`).style.width=`${Math.min(100,Math.max(0,v))}%`}const m=Math.max(...p),i=p.indexOf(m);$("prediction-text").textContent=m?`設定予測：設定${i+1}が最有力　（判別対象 ${targetGames()}G）`:"設定予測：判定材料不足"}
$("judge-btn")?.addEventListener("click",()=>{const g=targetGames();if(g<=0){alert("判別対象ゲーム数を入力してください。");return}render(probabilities());$("result-section").classList.add("visible");$("result-section").scrollIntoView({behavior:"smooth",block:"start"})});
$("reset-btn")?.addEventListener("click",()=>{Object.keys(state).forEach(k=>state[k]=typeof state[k]==="number"?0:state[k]);state.minSetting=1;["games","start-games"].forEach(id=>{if($(id))$(id).value=""});document.querySelectorAll("[id$='-value']").forEach(e=>e.textContent="0");document.querySelectorAll(".material-grid button,.material-list button").forEach(b=>b.classList.remove("selected"));for(let s=1;s<=6;s++){if($(`setting-percent-${s}`))$(`setting-percent-${s}`).textContent="0%";if($(`setting-bar-${s}`))$(`setting-bar-${s}`).style.width="0%"}$("prediction-text").textContent="-";$("result-section").classList.remove("visible")});
});